
spring:
  application:
    name: msvc-eureka

# eureka-server.yml en el Config Server (repositorio git u otro)
server:
  port: 8761  # Puerto donde se ejecuta Eureka

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL de registro de Eureka para los clientes
  instance:
    prefer-ip-address: true
